# Generated by Django 4.2.1 on 2024-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyamenity',
            old_name='name',
            new_name='items_name',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='hotel',
            field=models.ManyToManyField(to='app.add_hotel'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='room',
            field=models.ManyToManyField(to='app.add_room'),
        ),
    ]
