# Generated by Django 4.2.1 on 2023-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_branch_hotel_hotelowner_delete_add_room_hotel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='mobile',
            field=models.CharField(default='', max_length=12),
        ),
    ]
