# Generated by Django 4.2.1 on 2023-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotelowner_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Number_of_rooms',
            field=models.CharField(default='', max_length=100),
        ),
    ]
