# Generated by Django 4.2.1 on 2024-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
