# Generated by Django 4.2.1 on 2023-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Superadmin'), ('2', 'User')], default='Superadmin', max_length=10),
        ),
    ]
