# Generated by Django 4.2.1 on 2023-12-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=50)),
                ('room_image', models.ImageField(upload_to='room_img')),
                ('flat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_hotel')),
            ],
        ),
    ]
