# Generated by Django 4.2.1 on 2023-12-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_user',
        ),
    ]
