# Generated by Django 4.2.1 on 2023-12-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_add_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('user_image', models.ImageField(upload_to='user_img')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_hotel')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='add_users')),
            ],
        ),
    ]
