# Generated by Django 4.2.1 on 2023-12-20 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=50)),
                ('select_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_hotel')),
                ('select_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='add_users')),
            ],
        ),
    ]
